Allowed bridge parameters to be serialized
firesim/firesim pull request #1141
Opened 2022-07-21 08:05 UTC by nandor

Bridge annotations can now can be serialized and constructed using `widgetConstructorKey`.
Instead of passing multiple arguments and requiring a lambda in the annotation, parameters are 
now wrapped in a case class that can be instantiated using the `widgetConstructorKey` mechanism.

#### Related PRs / Issues

None.

#### UI / API Impact

None.

#### Verilog / AGFI Compatibility

No changes.

### Contributor Checklist
- [x] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you add Scaladoc/docstring/doxygen to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous prints/debugging code?
- [x] Did you state the UI / API impact?
- [x] Did you specify the Verilog / AGFI compatibility impact?

- [ ] If applicable, did you regenerate and publicly share default AGFIs?

- [ ] If applicable, did you apply the `ci:fpga-deploy` label?

- [ ] If applicable, did you apply the `Please Backport` label?

### Reviewer Checklist (only modified by reviewer)
- [ ] Is the title suitable for inclusion in the changelog and does the PR have a `changelog:<topic>` label?
- [ ] Did you mark the proper release milestone?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?

2022-07-21 17:53 UTC, davidbiancolin requested changes
A nice change. I only have a few nits, mostly just the string encoding of a class name.

2022-07-21 17:53 UTC, davidbiancolin commented on sim/midas/src/main/scala/midas/widgets/AssertBridge.scala
> +  val assertPortName = key.assertPortName
This is neither here nor there, but you can destructure the case class with its unapply method like so:
` val AssertBridgeParameters(assertPortName, resetPortName, assertMessages) = key`

2022-07-21 17:53 UTC, davidbiancolin commented on sim/midas/src/main/scala/midas/widgets/ClockBridge.scala
> +  * @param key Clock frequency information for each target clock
Since ScalaDoc was provided for this class could you add some for `ClockKey` and update this accordingly.

2022-07-21 17:53 UTC, davidbiancolin commented on sim/midas/src/main/scala/midas/widgets/ClockBridge.scala
> +      widgetClass = Some("midas.widgets.ClockBridgeModule"),
```suggestion
      widgetClass = Some(classOf[ClockBridgeModule].getName),
```
Should work.

2022-07-22 15:00 UTC, nandor commented
Thanks for the comments. Managed to revert back to the lambda and avoid hardcoding class names/references altogether.

2022-07-28 01:00 UTC, davidbiancolin approved these changes
LGTM

2022-07-28 06:04 UTC, merged