Introduced a uniform harness across all simulations
firesim/firesim pull request #1342
Opened 2022-12-21 12:16 UTC by nandor

Moved the post-simulation dumps of `fasedtests` and `firesim` to `simulation_t` to de-duplicate the logic and to print out the same information across all simulation, including `midasexamples`.

This is necessary to clean up `simif_t` by decoupling non-IO related logic.

`simulation_t` now exposes a callback to check whether the simulation timed out. In the future, such timeout logic should be introduced and respected across `midasexamples` as well.

#### Related PRs / Issues

#### UI / API Impact

`midasexamples` and all simulations will print out the exit status and the cycle count.

#### Verilog / AGFI Compatibility

### Contributor Checklist
- [x] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you add Scaladoc/docstring/doxygen to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous prints/debugging code?
- [x] Did you state the UI / API impact?
- [x] Did you specify the Verilog / AGFI compatibility impact?

- [ ] If applicable, did you regenerate and publicly share default AGFIs?

- [ ] If applicable, did you apply the `ci:fpga-deploy` label?

- [ ] If applicable, did you apply the `Please Backport` label?

### Reviewer Checklist (only modified by reviewer)
Note: to run CI on PRs from forks, comment `@Mergifyio copy main` and manage the change from the new PR.
- [ ] Is the title suitable for inclusion in the changelog and does the PR have a `changelog:<topic>` label?
- [ ] Did you mark the proper release milestone?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?

2022-12-22 00:59 UTC, sifive-benjamin-morse requested changes
looks good to me

2022-12-22 00:59 UTC, sifive-benjamin-morse commented on sim/midas/src/main/cc/simif.cc
> +  double fmr = ((double)hcycles / end_tcycle);
```suggestion
  const uint64_t hcycles = end_hcycle - start_hcycle;
  const double sim_time = diff_secs(end_time, start_time);
  const double sim_speed = ((double)end_tcycle) / (sim_time * 1000.0);
  const double measured_host_frequency = ((double)hcycles) / (sim_time * 1000.0);
  const double fmr = ((double)hcycles / end_tcycle);
```

I think const correctness dictates that these should be const

2022-12-22 00:59 UTC, sifive-benjamin-morse commented on sim/midas/src/main/cc/simif.cc
> +  bool timeout = simulation_timed_out();
```suggestion
  const bool timeout = simulation_timed_out();
```

2023-01-04 22:45 UTC, sifive-benjamin-morse approved these changes
looks good!

2023-01-05 10:20 UTC, nandor commented
This is a fairly straightforward refactoring - I will be merging it since rebasing this creates a bunch of conflicts. After the introduction of the widget registry there will be a great opportunity to clear up the simulation setup flow.

2023-01-05 14:42 UTC, merged