Separate XSIM from f1 into simif_xsim
firesim/firesim pull request #1374
Opened 2023-01-07 16:43 UTC by nandor

The XSIM implementation is largely disjoint from the F1 one. Separate it.

#### Related PRs / Issues

#### UI / API Impact

#### Verilog / AGFI Compatibility

### Contributor Checklist
- [x] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you add Scaladoc/docstring/doxygen to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous prints/debugging code?
- [x] Did you state the UI / API impact?
- [x] Did you specify the Verilog / AGFI compatibility impact?

- [ ] If applicable, did you regenerate and publicly share default AGFIs?

- [ ] If applicable, did you apply the `ci:fpga-deploy` label?

- [ ] If applicable, did you apply the `Please Backport` label?

### Reviewer Checklist (only modified by reviewer)
Note: to run CI on PRs from forks, comment `@Mergifyio copy main` and manage the change from the new PR.
- [ ] Is the title suitable for inclusion in the changelog and does the PR have a `changelog:<topic>` label?
- [ ] Did you mark the proper release milestone?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?

2023-01-09 17:25 UTC, davidbiancolin requested changes
So "simif_xsim" is very closely tied to F1. It would be preferable to have the xsim implementation be built alongside the deployment driver, and selected at runtime if possible, instead of separating them into separate targets in the Makefile. This is more consistent with how vitis works, and minimizes the user-facing + build system changes until we can figure out how to more intelligently support FPGA-level metasimulation from a build-system perspective.

2023-01-09 17:34 UTC, nandor commented
In its present form, `simif_f1` is bad engineering. Based on the platform-specific flag, both the method implementations and the class members are different and almost fully disjoint. The executables produced are still the same as the change is hidden behind the Makefile in the driver directory. The PLATFORM flag is the same, we simply choose a different simif file. We do not need any conditional compilation in driver code and splitting stuff into two classes fully solves that. In a subsequent change, the main method will be de-duplicated as well and the scope of `simif` will be almost narrowed to handling the interface to hardware/simulation, as it should be.

2023-01-09 23:21 UTC, nandor commented
Thanks for specifying the new name. I am sorry for causing stress due to this process, however bugs are being fixed and technical debt is being burnt off.

2023-01-10 00:19 UTC, nandor commented
I can't get xsc/xvlog to work on internal machines, but the flow works up until that point and the binary is build and reaches the point of opening the file handles. No documentation changes are needed.

2023-01-12 18:59 UTC, davidbiancolin approved these changes

2023-01-12 21:09 UTC, merged