Add option to F1 driver to load an AGFI
firesim/firesim pull request #1434
Opened 2023-02-17 12:51 UTC by nandor

If the `+agfi=` option points to an AGFI, the image is loaded before the simulation starts.

#### Related PRs / Issues

#### UI / API Impact

#### Verilog / AGFI Compatibility

### Contributor Checklist
- [x] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you add Scaladoc/docstring/doxygen to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous prints/debugging code?
- [x] Did you state the UI / API impact?
- [x] Did you specify the Verilog / AGFI compatibility impact?

- [ ] If applicable, did you regenerate and publicly share default AGFIs?

- [ ] If applicable, did you apply the `ci:fpga-deploy` label?

- [ ] If applicable, did you apply the `Please Backport` label?

### Reviewer Checklist (only modified by reviewer)
Note: to run CI on PRs from forks, comment `@Mergifyio copy main` and manage the change from the new PR.
- [ ] Is the title suitable for inclusion in the changelog and does the PR have a `changelog:<topic>` label?
- [ ] Did you mark the proper release milestone?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?

2023-02-17 17:01 UTC, timsnyder-siv requested changes
You seem to be passing the AGFI to a function that is documented as taking the AFI.

2023-02-17 17:15 UTC, nandor commented on sim/midas/src/main/cc/simif_f1.cc
> +    int rc = fpga_mgmt_load_local_image(slot_id, data.get());
https://github.com/aws/aws-fpga/blob/master/sdk/userspace/fpga_mgmt_tools/README.md#asynchronously-loading-an-afi-to-a-specific-fpga-slot

It seems like the AGFI is required. When I tried using the `afi-*` ids, this failed.

2023-02-17 17:41 UTC, timsnyder-siv commented on sim/midas/src/main/cc/simif_f1.cc
> +    int rc = fpga_mgmt_load_local_image(slot_id, data.get());
I see how the header file for the C api and their markdown documentation are conflicting.

2023-02-17 18:27 UTC, timsnyder-siv requested changes

2023-02-17 18:27 UTC, timsnyder-siv commented on sim/midas/src/main/cc/simif_f1.cc
> +    // Load the image.
To ensure that the FPGA is loaded into a well-defined state, you should `fpga_mgmt_clear_local_image(slot_id)` before loading the image as suggested in https://github.com/aws/aws-fpga/blob/master/hdk/README.md#step5 and to align with the way the manager loads the AGFI.

2023-02-19 03:13 UTC, fabianschuiki approved these changes
LGTM! It's good to have the option of directly passing the AGFI to the driver  for convenience :+1:

2023-02-21 15:50 UTC, timsnyder-siv approved these changes
Hopefully clearing and loading the AGFI is enough to get you into a useful and reliable state.

2023-02-21 17:00 UTC, merged