Add option to remove -retiming flag from Vivado
firesim/firesim pull request #728
Opened 2021-02-25 22:12 UTC by jerryz123

Depends on https://github.com/firesim/aws-fpga-firesim/pull/34

2021-02-26 01:26 UTC, davidbiancolin approved these changes
LGTM. 

Though you might consider using a different base strategy if you're disabling retiming, since in many cases your fmax is going to be poor (e.g., basic, explore). Some of the other strats have significantly better runtime.

2021-02-26 02:37 UTC, timsnyder-siv commented
Is there something specific you're running into that you need to avoid the `-retiming` option?  I'm curious to know more.

2021-02-26 02:45 UTC, jerryz123 commented
Our machine learning accelerator design utilizes many floating-point pipelines, which must be retimed. However, when the `-retiming` flag is enabled, Vivado will sometimes crash consistently with an internal error during the retiming passes, regardless of what target frequency I set.

Removing the retiming flag prevents the crash, and lets the design build successfully. 

David and I both suspect that updating to a newer version of Vivado might solve the issue, so this is an interim solution.

2021-02-26 02:59 UTC, timsnyder-siv commented
Ok.  I'm also interested in why `-retiming` isn't correctly retiming a block that I expect to be retimed in one of our cores (haven't seen the crash yet).  I was trying to look through the Vivado docs to learn more about the requirements for being able to retime.  I see messages in our log about some modules being retimed  and many others being skipped because their effective depth is much lower than the effective depth of the entire design but I see no mention of the module that ends up having the WNS path (that also happens to have gate depth equal to the one I was seeing in the retiming messages).

I was curious whether you guys have ever tried do anything with `rocketchip.util.RetimeModuleAnnotation` feeding into constraints for Vivado.

If newer Vivado doesn't fix the problem, we should definitely add this to the list of things to bring up with the Vivado devs and I'm happy to help push on that.

@davidbiancolin can we put this topic on the agenda for next Tuesday?

2021-02-26 04:11 UTC, davidbiancolin commented
> @davidbiancolin can we put this topic on the agenda for next Tuesday?

Sure thing. 

There's a long history of Vivado retiming not working for our designs, so i'm not altogether surprised.

2021-03-11 20:34 UTC, jerryz123 commented
Not sure why this is failing CI

2021-03-11 22:29 UTC, abejgonzalez commented on sim/firesim-lib/src/main/scala/util/Configs.scala
> +class NoRetiming extends WithBuildStrategy(BuildStrategies.NoRetiming)
```suggestion
class Congestion extends WithBuildStrategy(BuildStrategies.Congestion)
class Timing extends WithBuildStrategy(BuildStrategies.Timing)
class Explore extends WithBuildStrategy(BuildStrategies.Explore)
class NoRetiming extends WithBuildStrategy(BuildStrategies.NoRetiming)
```

2021-03-11 22:30 UTC, abejgonzalez requested changes

2021-03-11 22:30 UTC, abejgonzalez commented on sim/firesim-lib/src/main/scala/util/Configs.scala
> +class NoRetiming extends WithBuildStrategy(BuildStrategies.NoRetiming)
Additionally, the config. fragment needs to be changed from `WithBuildStategy` to `WithBuildStrategy`

2021-03-11 22:57 UTC, abejgonzalez approved these changes
Yay spelling!

2021-03-24 18:21 UTC, jerryz123 commented
Can this be merged? Not sure why CI is failing

2021-03-24 18:51 UTC, davidbiancolin commented
Can you rebase it and run CI again?

2021-03-30 04:21 UTC, merged